Icon updater
botblock/BotBlock.org pull request #19
Opened 2019-10-08 19:11 UTC by DetectiveHuman

* Added mass icon updater.
* Fixed manual icon updater.

2019-10-08 19:25 UTC, MattIPv4 commented on src/Dynamic/lists/iconupdater.pug
> +                            #{lists.map((m) => m).join('<br>')}
```suggestion
                            #{lists.map((m) => m).join('<br/>')}

```
Self-closing tag, ending line break.

2019-10-08 20:56 UTC, MattIPv4 requested changes

2019-10-08 20:56 UTC, MattIPv4 commented on src/Routes/Lists.js
> +                    }
Why is this indented?

2019-10-08 20:56 UTC, MattIPv4 commented on src/Routes/Lists.js
> -
Unrelated change?

2019-10-08 21:08 UTC, DetectiveHuman commented on src/Routes/Lists.js
> +                    }
Fixed.

2019-10-09 16:56 UTC, MattIPv4 reviewed
This doesn't appear to be working as expected in dev, not sure why.
![image](https://user-images.githubusercontent.com/12371363/66502879-0d56f800-eabe-11e9-8800-2860c8e75fbb.png)

2019-12-30 21:39 UTC, MattIPv4 commented
Closing as discussed in Discord.

2019-12-30 21:39 UTC, closed without merging